// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwrewjcupchmbcenrhnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3cmV3amN1cGNobWJjZW5yaG5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDE3OTEsImV4cCI6MjA2MDI3Nzc5MX0.sJHBMadsZFTfC8cgNJgpdeCMFHPA9610dc_pugrF4l4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);